[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/alternatives"
to = "/.netlify/functions/alternatives-background"
status = 200
force = false



[[redirects]]
from = "/api/compare"
to = "/.netlify/functions/compare"
status = 200
force = false

